debugging: true

command:
  anti-syntax-message: "&cYou cannot execute {argument}."
  # Allows you to execute for example alley:alley (syntax)
  syntax-bypass-perm: "alley.owner"
  # The dispatched/executed command by console when the players buys a cosmetic
  grant-cosmetic-permission-command: "permission set {player} {permission}"

spawn:
  # The spawn location of the server
  join-location: world:0.5:73.0:0.5:90.0:0.0

game:
  # In kits with lives setting enabled, this is the void (y) level where the player will die/lose a point.
  # [!] Must be within the cuboid of the arena.
  death-y-level: 10
  # The amount of lives each player will have in a lives match.
  lives: 3

arena:
  # When creating an arena, the following displayname for each
  # arena type will be set. {arena} represents the arena name.
  default-display-name:
    shared: "&b{arena}"
    standalone: "&b{arena}"
    ffa: "&b{arena}"

kit:
  # The default name and description that's going to be set when creating a kit.
  default-name: "&b&l{kit}"
  default-description: "&7{description} kit description."